version: '2'
services:
  nginx-certbot:
    image: lukasdornak/nginx-certbot
    stdin_open: true
    volumes:
    - /data/proxy/letsencrypt:/etc/letsencrypt:rw
    - /data/proxy/sites:/etc/nginx/conf.d:rw
    tty: true
    ports:
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.container.pull_image: always